package com.netctoss.entity;

import java.util.HashSet;
import java.util.Set;

import com.netctoss.util.PrivilegeReader;

/**
 * Role generated by MyEclipse Persistence Tools
 */

public class Role implements java.io.Serializable {

    // Fields

    private int id;

    private String name;
    //为了接收表单的权限id信息，添加的属性
    private String[] ids;
    //追加属性，用于存储相关的RolePrivilege信息
    private Set<RolePrivilege> privileges;

    // Constructors

    public String getPrivilegeNames() {
        StringBuffer buf = new StringBuffer();
        for (RolePrivilege rp : privileges) {
            Integer privilegeId = rp.getId().getPrivilegeId();
            String name = PrivilegeReader.getPrivilegeNameById(privilegeId.toString());
            buf.append(name);
            buf.append(" ");
        }
        return buf.toString();
    }

    public Set<RolePrivilege> getPrivileges() {
        return privileges;
    }


    public void setPrivileges(Set<RolePrivilege> privileges) {
        this.privileges = privileges;
    }


    public String[] getIds() {
        return ids;
    }


    public void setIds(String[] ids) {
        this.ids = ids;
    }


    /**
     * default constructor
     */
    public Role() {
    }


    // Property accessors

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}